name: Build and deploy to GitHub Pages
on:
  push:
    branches: ["live"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: enable corepack
      run: corepack enable
    - name: set up node
      uses: actions/setup-node@v4
      with:
        node-version: "lts/*"
        cache: yarn
    - name: setup pages
      uses: actions/configure-pages@v4
    - name: restore cache
      uses: actions/cache@v4
      with:
        path: |
          .next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
    - name: validate dependencies
      run: yarn install --immutable --immutable-cache --check-cache
    - name: build
      run: yarn next build
    - name: upload build artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./out
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: deploy
      id: deployment
      uses: actions/deploy-pages@v4